### ISSUE TITLE
How to Set Multi-Pipeline Functions in a Service

### ISSUE THREAD

**Issue by rwxdfbb** [edgexfoundry/app-service-configurable#205]
Currently, one requirement is to push data from coredata to the cloud and receive messages from the cloud and send the messages to the command microservice for processing. One pipeline cannot meet the preceding requirements. However, the app SDK does not support multiple pipelines. Is there any good idea?

**Comment by lenny-intel** [comment]
@rwxdfbb , how are you receiving messages from the Cloud to send commands? If you are using the `external-mqtt` trigger, then you must use two separate Application Services to accomplish these two separate tasks. Note that `app-service-configurable` works great for export unless you have custom transform of the data prior to exporting. 
https://docs.edgexfoundry.org/1.3/microservices/application/AppServiceConfigurable/

Please let me know if this answered your question.

**Comment by AlexCuse** [comment]
Expanding on Lenny's comment here a little, we find it helpful here to consider our applications in terms of a two lane highway.  The northbound lane is the edge to cloud pipeline, and the southbound lane cloud to edge.  It makes visualizing and discussing them much easier, and provides a line to organize port mappings etc along when we are configuring services to create a deployed application.  Even if it was possible to support multiple pipelines in a single service, I think I would split things up along these lines just to maximize ease of use / reuse, and better support different scaling needs (for example depending on message flow rates you may need multiple publishers and one listener in an application, or vice versa)

Go won't actually *stop* you from for example setting up an MQTT listener in your publishing service and dispatching commands in the background, but EdgeX makes it somewhat difficult to use several of its underlying components in this fashion, by design.  Once you are doing something like that you really lose most of what EdgeX gives you - a stable, well managed execution pipeline to run your code inside, and support for common application needs like configuration, logging, message retries etc.

**Comment by rwxdfbb** [comment]
> @rwxdfbb , how are you receiving messages from the Cloud to send commands? If you are using the `external-mqtt` trigger, then you must use two separate Application Services to accomplish these two separate tasks. Note that `app-service-configurable` works great for export unless you have custom transform of the data prior to exporting.
> https://docs.edgexfoundry.org/1.3/microservices/application/AppServiceConfigurable/
> 
> Please let me know if this answered your question.

I have a simple application scenario: The application service is connected to the cloud through the websocket. The local inference result data is processed through the pipeline, filtering and compression are added, and then sent to the cloud. Both cloud-based query and configuration are supported. However, I found the following problems:
1. Because the service is simple, I do not want to enable two services. However, two pipelines cannot be defined for the same microservice to process both uplink and downlink data.
2. Currently, the pipeline function provided by the application service configurable is only an export interface, and the data processing function from the cloud is missing.
3. External interfaces support only MQTT and HTTP, but do not support WebSocket. If WebSocket is used, I need to develop a program to connect to the cloud. How can I set the event trigger from the cloud?

**Comment by lenny-intel** [comment]
> * Because the service is simple, I do not want to enable two services. However, two pipelines cannot be defined for the same microservice to process both uplink and downlink data.
Correct, only one pipeline for processing data for the configured trigger (aka binding)

> * Currently, the pipeline function provided by the application service configurable is focuses on the export interface, but the data processing function from the cloud is missing.
What data processing is missing? Do you need the data to be reformatted?

> * External interfaces support only MQTT and HTTP, but do not support WebSocket. If WebSocket is used, I need to develop a program to connect to the cloud. How can I set the event trigger from the cloud?
Correct, WebSocket is not a supported trigger or export protocol. The `external-mqtt` trigger was added to allow trigger from cloud. base MQTT broker.

> * How to set multiple topics？
Multiple subscribe topics? of publish topics?
Currently only support one of each, but in the next release the App Service will support multiple subscribe topics.

**Comment by rwxdfbb** [comment]
> > * Because the service is simple, I do not want to enable two services. However, two pipelines cannot be defined for the same microservice to process both uplink and downlink data.
> 
> Correct, only one pipeline for processing data for the configured trigger (aka binding)
> 
> > * Currently, the pipeline function provided by the application service configurable is focuses on the export interface, but the data processing function from the cloud is missing.
> 
> What data processing is missing? Do you need the data to be reformatted?
> 
> > * External interfaces support only MQTT and HTTP, but do not support WebSocket. If WebSocket is used, I need to develop a program to connect to the cloud. How can I set the event trigger from the cloud?
> 
> Correct, WebSocket is not a supported trigger or export protocol. The `external-mqtt` trigger was added to allow trigger from cloud. base MQTT broker.
> 
> > * How to set multiple topics？
> 
> Multiple subscribe topics? of publish topics?
> Currently only support one of each, but in the next release the App Service will support multiple subscribe topics.

Thank you. I understand the design idea and basic usage through communication.
