### ISSUE TITLE
Need support to export Event data on the REST Endpoint

### ISSUE THREAD

**Issue by pachori91** [edgexfoundry/app-service-configurable#571]
Hi Team,

I have started Edgex by using https://github.com/edgexfoundry/edgex-compose/blob/v3.0/docker-compose-no-secty-with-app-sample.yml. 

Further i just inserted json data to the Edgex by using Device-Rest Service by calling http://localhost:59986/api/v3/resource/2way-rest-device/json.

Now i need to convert format of event data and then export the event data to external REST Endpoint.

Can someone please suggest me for same?
 
Thanks

**Comment by lenny-intel** [comment]
@pachori91 , in the future please post question like this to https://github.com/orgs/edgexfoundry/discussions 

See the docs for App Service Configurable HTTP Export here: https://docs.edgexfoundry.org/3.0/microservices/application/AppServiceConfigurable/#http-export

**Comment by kumardeepak5** [comment]
Hi Team,

I just tried to debug code of App Service configurable.

But could not found where environment varibale(WRITABLE_PIPELINE_FUNCTIONS_HTTPEXPORT_PARAMETERS_URL) are parsed and used in code?

can someone please help me on same.

**Comment by kumardeepak5** [comment]
hi Team,

i have created a new app-services-configurable by using local copy of app-funstions-sdk-go and able to build by using **"make build" and" make docker"** command to create docker image of my custom app-service-configurable. 
But i want to run app-service-configurable(with local copy of app-functions-sdk-g) in dev environment where i can debug code and put breakpoint. i am using VS code.

where i am blocked - 
1. how to integrate custom app-service-configurable with other services like core command, devices service(running by docker setup).
Purpose - i want to debug how app-configurable service handling device data while using http-export profile.


Please suggest me step for same so that i can debug it 

Thanks
Deepak Kumar

**Comment by lenny-intel** [comment]
> Now i need to convert format of event data and then export the event data to external REST Endpoint.

@pachori91 , what formatting do you need? App Service Configurable has limited formatting options (JSOM & XML). 
https://docs.edgexfoundry.org/3.0/microservices/application/AppServiceConfigurable/#transform

If that doesn't meet your needs you need to create a custom app service with a custom formatting Pipeline Function.
https://docs.edgexfoundry.org/3.0/microservices/application/ApplicationServices/#standard-functions
https://docs.edgexfoundry.org/3.0/microservices/application/GettingStarted/#custom 

 For HTTP export see the docs for App Service Configurable HTTP Export here: https://docs.edgexfoundry.org/3.0/microservices/application/AppServiceConfigurable/#http-export
or for use in custom app service see here: 
https://docs.edgexfoundry.org/3.0/microservices/application/BuiltIn/#http-export

**Comment by lenny-intel** [comment]
@kumardeepak5 , please do not hijack an existing issue to ask a separate question. Please submit your question at https://github.com/orgs/edgexfoundry/discussions

**Comment by lenny-intel** [comment]
closing issue as answered
